/**
 * Mighty Verse Scene Candidates
 *
 * Defines the explicit distinction between an AI/CV-generated Scene candidate
 * and a canonical Scene.
 *
 * A candidate is EVIDENCE — it must be reviewed and accepted by an operator
 * before it becomes a canonical Scene in the database.
 *
 * NEVER write SceneCandidate records directly into the master/canonical_state tables.
 * NEVER treat a SceneCandidate as a canonical Scene.
 *
 * The operator workflow is:
 *   SceneCandidate → review → accept/reject/adjust → canonical Scene (via authority API)
 */

/** Source of a scene candidate — what generated it. */
export type CandidateSource =
  | "browser-visual-change"   // Visual change detection from frame sampling
  | "browser-audio-energy"    // Audio energy analysis (future)
  | "operator-manual"         // Operator manually proposed a boundary
  | "external-metadata";      // From an external metadata source (e.g. chapter markers)

/** Confidence level of a candidate boundary. */
export type CandidateConfidence = "high" | "medium" | "low";

/**
 * A candidate Scene boundary proposed by the intelligence layer.
 *
 * This is NOT a canonical Scene. It is evidence for the operator to review.
 * It has no master_id, no canonical_state_id, no projection_id.
 * It is ephemeral — it lives in browser state or a temporary evidence store.
 */
export type SceneCandidate = {
  /**
   * Ephemeral candidate identifier.
   * Generated client-side (e.g. crypto.randomUUID()).
   * NOT a canonical database UUID.
   */
  candidateId: string;

  /** Proposed start time in milliseconds. */
  startMs: number;

  /** Proposed end time in milliseconds. Null if this is a boundary-only proposal. */
  endMs: number | null;

  /** Confidence in this candidate. */
  confidence: CandidateConfidence;

  /**
   * Normalised change score 0–1 from visual analysis.
   * Null for manually-proposed candidates.
   */
  changeScore: number | null;

  /** What generated this candidate. */
  source: CandidateSource;

  /**
   * Representative frame data URL (base64 JPEG) at the candidate boundary.
   * Used for visual review. Null if not available.
   */
  representativeFrame: string | null;

  /**
   * Operator review state.
   * "pending" = not yet reviewed.
   * "accepted" = operator accepted → will become canonical Scene.
   * "rejected" = operator rejected → discarded.
   * "adjusted" = operator modified the boundary.
   */
  reviewState: "pending" | "accepted" | "rejected" | "adjusted";

  /**
   * Operator-adjusted start time in milliseconds.
   * Only set when reviewState = "adjusted".
   */
  adjustedStartMs?: number;

  /**
   * Operator-adjusted end time in milliseconds.
   * Only set when reviewState = "adjusted".
   */
  adjustedEndMs?: number;

  /**
   * Operator-proposed title for the Scene.
   * Only set after operator review — never auto-generated from AI.
   */
  proposedTitle?: string;
};

/**
 * The result of a full media inspection session.
 * Contains candidates and the evidence that produced them.
 * This is ephemeral — it is not persisted to Supabase.
 */
export type InspectionSession = {
  /** Ephemeral session identifier. */
  sessionId: string;

  /** The media asset being inspected (Mighty Verse asset_id if known). */
  assetId: string | null;

  /** The playback source URL that was inspected. */
  playbackUrl: string;

  /** Duration of the inspected media in milliseconds. */
  durationMs: number | null;

  /** Video dimensions. Null for audio-only. */
  dimensions: { width: number; height: number } | null;

  /** When the inspection was performed (ISO string). */
  inspectedAt: string;

  /** All candidates generated by this session. */
  candidates: SceneCandidate[];
};

/**
 * Create a new ephemeral inspection session.
 */
export function createInspectionSession(opts: {
  assetId: string | null;
  playbackUrl: string;
  durationMs: number | null;
  dimensions: { width: number; height: number } | null;
}): InspectionSession {
  return {
    sessionId: typeof crypto !== "undefined" ? crypto.randomUUID() : `session-${Date.now()}`,
    assetId: opts.assetId,
    playbackUrl: opts.playbackUrl,
    durationMs: opts.durationMs,
    dimensions: opts.dimensions,
    inspectedAt: new Date().toISOString(),
    candidates: [],
  };
}

/**
 * Convert candidate boundary timestamps into SceneCandidate objects.
 * Pairs consecutive boundaries into start/end intervals.
 *
 * @param timestamps  Boundary timestamps in milliseconds (sorted ascending).
 * @param durationMs  Total media duration in milliseconds.
 * @param frames      Representative frame data URLs indexed by timestamp (ms).
 * @param changeScores Change scores indexed by timestamp (ms).
 */
export function timestampsToCandidates(
  timestamps: number[],
  durationMs: number,
  frames: Map<number, string> = new Map(),
  changeScores: Map<number, number> = new Map()
): SceneCandidate[] {
  if (timestamps.length === 0) return [];

  // Build boundary list: always start from 0, end at durationMs
  const boundaries = [0, ...timestamps, durationMs];

  return boundaries.slice(0, -1).map((startMs, i) => {
    const endMs = boundaries[i + 1];
    const score = changeScores.get(startMs) ?? null;
    const confidence: CandidateConfidence =
      score == null ? "medium"
      : score >= 0.4 ? "high"
      : score >= 0.2 ? "medium"
      : "low";

    return {
      candidateId: typeof crypto !== "undefined" ? crypto.randomUUID() : `candidate-${i}-${Date.now()}`,
      startMs,
      endMs,
      confidence,
      changeScore: score,
      source: "browser-visual-change" as CandidateSource,
      representativeFrame: frames.get(startMs) ?? null,
      reviewState: "pending" as const,
    };
  });
}

/**
 * Accept a candidate — operator has approved this boundary.
 * Returns a new candidate with reviewState = "accepted".
 * Does NOT create a canonical Scene — that requires the authority API.
 */
export function acceptCandidate(candidate: SceneCandidate): SceneCandidate {
  return { ...candidate, reviewState: "accepted" };
}

/**
 * Reject a candidate — operator has discarded this boundary.
 */
export function rejectCandidate(candidate: SceneCandidate): SceneCandidate {
  return { ...candidate, reviewState: "rejected" };
}

/**
 * Adjust a candidate's boundaries — operator has modified the proposed interval.
 */
export function adjustCandidate(
  candidate: SceneCandidate,
  adjustedStartMs: number,
  adjustedEndMs: number
): SceneCandidate {
  return {
    ...candidate,
    reviewState: "adjusted",
    adjustedStartMs,
    adjustedEndMs,
  };
}

/**
 * Get the effective start/end for a candidate (adjusted if available).
 */
export function effectiveBoundary(candidate: SceneCandidate): { startMs: number; endMs: number | null } {
  if (candidate.reviewState === "adjusted" && candidate.adjustedStartMs != null) {
    return {
      startMs: candidate.adjustedStartMs,
      endMs: candidate.adjustedEndMs ?? candidate.endMs,
    };
  }
  return { startMs: candidate.startMs, endMs: candidate.endMs };
}
